

CREATE DATABASE idoneo;
USE idoneo ;

CREATE TABLE users (
 id INT NOT NULL AUTO_INCREMENT,
 username VARCHAR(25) NOT NULL,
 PASSWORD VARCHAR(255) NOT NULL,
 NAME VARCHAR(255) NOT NULL,
 last_name VARCHAR(255) NOT NULL,
 PRIMARY KEY (id));